//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle: O({0},{1}), R = {2}, P = {3}, S = {4}
        ///.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rectangle cannot be built with the entered coordinates!
        ///.
        /// </summary>
        internal static string IncorrectCoordinatesWarning {
            get {
                return ResourceManager.GetString("IncorrectCoordinatesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu
        ///Type the number of the option you want to select:
        ///1.Build Straight Line
        ///2.Build Periphery
        ///3.Build Rectangle
        ///4.Build Circle
        ///5.Build Ring
        ///6.Display all figures
        ///To exit, press &apos;ESC&apos;
        ///.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius must be positive..
        /// </summary>
        internal static string NegativeRadiusWarning {
            get {
                return ResourceManager.GetString("NegativeRadiusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value for outer radius:.
        /// </summary>
        internal static string OuterRadiusOption {
            get {
                return ResourceManager.GetString("OuterRadiusOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periphery: O({0},{1}), R = {2}, P = {3}
        ///.
        /// </summary>
        internal static string Periphery {
            get {
                return ResourceManager.GetString("Periphery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle:
        ///A({0},{1})
        ///B({2},{3}))
        ///C({4},{5}))
        ///D({6},{7}))
        ///S = {8}
        ///P = {9}
        ///.
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring:
        ///O({0},{1})
        ///Inner R = {2}
        ///Outer R = {3}
        ///Inner P = {4}
        ///Outer P = {5}
        ///Inner S = {6}
        ///Outer S = {7}
        ///.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: A({0},{1}), B({2},{3})
        ///.
        /// </summary>
        internal static string StraightLine {
            get {
                return ResourceManager.GetString("StraightLine", resourceCulture);
            }
        }
    }
}
